"""Added the task_runs table

Revision ID: 8fb2e077b021
Revises: 29e0abb828f5
Create Date: 2024-01-29 01:16:26.768985

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8fb2e077b021"
down_revision = "29e0abb828f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("total_runtime", sa.Integer(), nullable=True),
        sa.Column(
            "files", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "files_added", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "files_deleted", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("magic_string_count", sa.Integer(), nullable=True),
        sa.Column("directory", sa.String(length=64), nullable=True),
        sa.Column("magic_string", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_runs_id"), "task_runs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_runs_id"), table_name="task_runs")
    op.drop_table("task_runs")
    # ### end Alembic commands ###
