"""Initial Empty Database Revision

Revision ID: 29e0abb828f5
Revises: None
Create Date: 2024-01-29 01:06:30.579666

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "29e0abb828f5"
down_revision = None
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
